name: JesusisGod
favicon: null
layout_spectrum: 0.6429352201521397
typography_spectrum: 0.509439131943509
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9924121773801744
  lightness: 0.2877621930092573
  saturation: 0.33691607927903533
  rhythmicContrast: 0.5109053766354918
purpose: []
